# SPDX-FileCopyrightText: Â© 2025 CoreWeave, Inc. <sunk@coreweave.com>

name: Commitlint

on:
  workflow_call:

permissions:
  contents: read
  packages: read # Required for pulling the cw actions images

jobs:
  commitlint:
    runs-on: cw
    container: ghcr.io/coreweave/github-actions-images/github-semantic-release:v1.8.0
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      # Fix a bug with corepack and setup-node caching
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "20"
      - name: Install packages
        run: |
          npm install conventional-changelog-conventionalcommits@7
          npm install commitlint@19
          npm install @commitlint/config-conventional@19
      - name: Validate current commit set with commitlint
        # `github.event.commits` only contains a maximum of 20 commits, so older commits will not
        # get checked.
        if: github.event_name == 'push'
        shell: bash
        run: |
          LENGTH=$(jq <<<'${{ toJSON(github.event.commits.*.id) }}' length)
          npx commitlint \
          --from ${{ github.event.after }}~"$LENGTH" \
          --to ${{ github.event.after }} \
          --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
          --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose
