# (c) 2025 by CoreWeave, Inc.
#
# This file is part of Slurm Containers.
#
# Slurm Containers is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Slurm Containers is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Slurm Containers; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA

name: Commitlint

on:
  workflow_call:

permissions:
  contents: read
  packages: read # Required for pulling the cw actions images

jobs:
  commitlint:
    runs-on: cw
    container: ghcr.io/coreweave/github-actions-images/github-semantic-release:v1.8.0
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      # Fix a bug with corepack and setup-node caching
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "20"
      - name: Install packages
        run: |
          npm install conventional-changelog-conventionalcommits@7
          npm install commitlint@19
          npm install @commitlint/config-conventional@19
      - name: Validate current commit set with commitlint
        # `github.event.commits` only contains a maximum of 20 commits, so older commits will not
        # get checked.
        if: github.event_name == 'push'
        shell: bash
        run: |
          LENGTH=$(jq <<<'${{ toJSON(github.event.commits.*.id) }}' length)
          npx commitlint \
          --from ${{ github.event.after }}~"$LENGTH" \
          --to ${{ github.event.after }} \
          --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
          --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose
