# SPDX-FileCopyrightText: Â© 2024 CoreWeave, Inc. <sunk@coreweave.com>

name: PR Orchestrator
on:
  pull_request:
    branches: ["main", "develop"]
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  packages: read # Required for pulling the cw actions images

jobs:
  commitlint:
    if: github.base_ref != 'main' && github.ref_name != 'develop' && github.ref_name != 'main'
    uses: ./.github/workflows/commitlint.yaml

  alls-green:
    if: always()
    needs:
      - commitlint
    runs-on: cw
    container: ghcr.io/coreweave/github-actions-images/github-base-runner:v1.7.0
    steps:
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.13"
      - name: Decide whether the needed jobs passed or failed.
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: commitlint
